In [20]:
import numpy as np

world_alcohol = np.genfromtxt("/home/simplon/Documents/world_alcohol.csv", delimiter=",", dtype="str", skip_header=1)
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [21]:
country_is_canada = world_alcohol[:,2] == 'Canada'
country_is_canada

array([False, False, False, ..., False, False, False])

In [22]:
country_canada = world_alcohol[world_alcohol[:,2] == 'Canada']
# country_canada = world_alcohol[country_is_canada]
print(country_canada)
print()
print(country_canada.shape)

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Wine' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Wine' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '']
 ['1985' 'Americas' 'Canada' 'Wine' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '']]

(20, 5)


In [23]:
country_algeria = world_alcohol[world_alcohol[:,2] == 'Algeria']
# country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)
print()
print(country_algeria.shape)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]

(20, 5)


In [24]:
annee_1984 = world_alcohol[world_alcohol[:,0] == '1984']
# annee_1984 = world_alcohol[year_is_1984]
print(annee_1984)
print()
print(annee_1984.shape)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]

(646, 5)


In [25]:
algeria_1986 = (world_alcohol[:,2] == 'Algeria') & (world_alcohol[:,0] == '1986')
row_algeria_1986 = world_alcohol[algeria_1986]
print(row_algeria_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


In [26]:
algeria_canada = (world_alcohol[:,2] == 'Algeria') | (world_alcohol[:,2] == 'Canada')
row_algeria_canada = world_alcohol[algeria_canada, :]
print(row_algeria_canada.shape)

(40, 5)


In [27]:
world_alcohol_2 = world_alcohol.copy()
print(world_alcohol_2[:,0])

['1986' '1986' '1985' ... '1986' '1987' '1986']


In [28]:
world_alcohol_2[world_alcohol[:,0] == "1986"]

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ...,
       ['1986', 'Western Pacific', 'Fiji', 'Spirits', '0.05'],
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U52')

In [29]:
world_alcohol_2[:,0][world_alcohol_2[:,0] == "1986"]

array(['1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
       '1986', '1986', '1986', '1986', '1986', '1986', '1986', '1986',
      

In [30]:
masque = (world_alcohol_2[:,0] == '1986')
world_alcohol_2[:,0][masque] = '2018'
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U52')

In [31]:
world_alcohol_2[:,3][world_alcohol_2[:,3] == "Wine"] = 'Beer'
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U52')

In [32]:
is_value_empty = (world_alcohol[:,4] == "")
is_value_empty

array([False, False, False, ..., False, False, False])

In [33]:
world_alcohol[is_value_empty,4] = '0'
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U52')

In [34]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)
alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

In [35]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()
print(total_alcohol)
print(average_alcohol)

3908.96
1.2001719373656738


In [45]:
total_consuption_1987_canada = (world_alcohol[:,0] == "1987") & (world_alcohol[:,2] == 'Canada')
row_total_consuption_1987_canada = world_alcohol[total_consuption_1987_canada]

print(alcohol_consumption_canada1987.sum())
print(alcohol_consumption_canada1987.mean())

9.120000000000001
2.2800000000000002


In [50]:
#consommation moyenne de biere pour les USA

consuption_mean_USA = (world_alcohol[:,1] == 'Americas') & (world_alcohol[:,3] == 'Beer')

total_consuption_USA = alcohol_consumption[consuption_mean_USA].sum()
average_consuption_USA = alcohol_consumption[consuption_mean_USA].mean()

print(total_consuption_USA)
print(average_consuption_USA)

310.02
2.0001290322580645


## Calculer la consommation pour chaque pays

- Tout d'abord, on crée un dictionnaire vide qui va contenir tous les pays et leurs consommations d'alcool associées, on le nommera totals.
- Sélectionner ensuite les lignes de world_alcohol correspondant à l'année donnée, disons 1989. Assigner le résultat à la variable year.
- Sélectionner dans une liste qu'on nommera countries tous les pays.
- Parcourir tous les pays de la liste à l'aide d'une boucle. Pour chaque pays:
    >- Sélectionner les lignes de year correpondant à ce pays
    >- Assigner le résultat à la variable country_consumption
    >- Extraire la 5e colonne de country_consumption
    >- Remplacer toute chaine de caractère vide dans cette colonne par 0
    >- Convertir la colonne en décimal (float)
    >- Calculer la somme de la colonne
    >- Ajouter la somme au dictionnaire totals, avec comme clé le nom du pays et en valeur cette somme.
- Afficher le dictionnaire totals.

In [83]:
totals = {}

countries = world_alcohol[:,2]
countriesD = set(countries)
countries = list(countriesD)

for i in countries :
    
    masque = (world_alcohol[:,0] == "1989") & (world_alcohol[:,2] == i)
    total_i = world_alcohol[masque,4].astype(float).sum()
    totals[i] = total_i
    
print(totals)

{'Haiti': 5.81, 'Thailand': 3.92, 'Madagascar': 1.38, 'Dominican Republic': 4.53, 'Qatar': 1.4500000000000002, 'Bolivia (Plurinational State of)': 3.05, 'Colombia': 6.960000000000001, 'Rwanda': 7.549999999999999, 'Indonesia': 0.07, 'Guatemala': 2.47, 'Togo': 2.2199999999999998, 'Australia': 12.09, 'Algeria': 0.4, 'Sweden': 7.47, 'Gambia': 1.6300000000000001, 'Japan': 7.74, 'Trinidad and Tobago': 4.68, 'Morocco': 0.7, 'Turkey': 0.72, 'Ukraine': 5.32, 'Djibouti': 0.87, 'Greece': 10.15, 'Albania': 1.73, 'Belize': 0.0, 'Myanmar': 0.16, 'Zimbabwe': 4.92, 'Ecuador': 2.54, 'Bahrain': 4.89, 'Panama': 4.6000000000000005, 'Kuwait': 0.0, 'Republic of Korea': 9.620000000000001, 'Paraguay': 6.51, 'Cuba': 4.37, 'Norway': 5.08, 'Egypt': 0.42000000000000004, 'Sierra Leone': 4.380000000000001, 'Sri Lanka': 0.14, 'Micronesia (Federated States of)': 0.0, 'Hungary': 16.29, 'France': 16.05, 'Israel': 2.0300000000000002, 'Sao Tome and Principe': 2.57, 'Niger': 0.11, 'Equatorial Guinea': 6.49, 'Luxembourg': 

## Trouver le pays qui consomme le plus d'alcohol

- Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
- Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
- Parcourir chaque pays du dictionnaire totals:
>- Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable highest_value et assigner la clé correspondante (nom du pays) à la variable highest_key.
- Afficher le pays qui consomme le plus d'alcool (variable highest_key)

In [84]:
highest_value = 0
highest_key = None

for (key,value) in totals.items():
    if value >= highest_value:
        highest_value = value
        highest_key = key

print(highest_key,highest_value)

Hungary 16.29


In [91]:
max = 0
maxCle = ''

for i in totals:
    if totals[i] > max:
        max = totals[i]
        maxCle = i

print(max,maxCle)

16.29 Hungary


## Puis ensuite créer une fonction qui aura pour argument d'entrée une année et retournera le dictionnaire contenant la consommation moyenne pour chaque pays

In [95]:
def total_dic(year):

    totals = {}

    is_year = (world_alcohol[:,0] == year)
    year_current = world_alcohol[is_year]
    countries = year_current[:,2]

    for country in countries:
        is_country = (year_current[:,2] == country)
        country_consumption = year_current[is_country]
        alcohol_column = country_consumption[:,4]
        is_empty_country_consumption = (alcohol_column == '')
        alcohol_column[is_empty_country_consumption] = '0'
        alcohol_column = alcohol_column.astype(float)
        totals[country] = alcohol_column.sum()

    return totals

total_1989 = total_dic('1989')
total_1989

{'Guatemala': 2.47,
 'Seychelles': 3.3000000000000003,
 'Costa Rica': 5.3999999999999995,
 'Mauritius': 3.54,
 'Zimbabwe': 4.92,
 'Suriname': 3.67,
 'Croatia': 10.92,
 'Syrian Arab Republic': 0.54,
 'Bolivia (Plurinational State of)': 3.05,
 'Somalia': 0.0,
 'Namibia': 0.24,
 'Uganda': 7.8,
 'Afghanistan': 0.0,
 'Jamaica': 3.03,
 'Finland': 9.419999999999998,
 'Iraq': 0.75,
 'Malawi': 1.02,
 'Bulgaria': 11.43,
 'Nicaragua': 2.5,
 'Central African Republic': 2.5199999999999996,
 'Burundi': 8.159999999999998,
 'Sweden': 7.47,
 'Greece': 10.15,
 'Kyrgyzstan': 4.279999999999999,
 'Belgium': 11.61,
 'Angola': 2.28,
 'Burkina Faso': 3.99,
 'Czech Republic': 13.009999999999998,
 'United Arab Emirates': 4.43,
 'Peru': 4.99,
 'Trinidad and Tobago': 4.68,
 'Guyana': 9.940000000000001,
 'Bahrain': 4.89,
 'Benin': 1.3800000000000001,
 'Liberia': 5.61,
 'Viet Nam': 0.16,
 'Belarus': 7.9799999999999995,
 'Swaziland': 6.68,
 'France': 16.05,
 'United States of America': 9.16,
 'Cabo Verde': 2.79,
 'S